package mybatis.mapper;

import java.util.List;
import mybatis.model.Category;
import org.mybatis.cdi.Mapper;

@Mapper
public interface CategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CATEGORY
     *
     * @mbg.generated Sat Mar 19 18:40:55 EET 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CATEGORY
     *
     * @mbg.generated Sat Mar 19 18:40:55 EET 2022
     */
    int insert(Category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CATEGORY
     *
     * @mbg.generated Sat Mar 19 18:40:55 EET 2022
     */
    Category selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CATEGORY
     *
     * @mbg.generated Sat Mar 19 18:40:55 EET 2022
     */
    List<Category> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CATEGORY
     *
     * @mbg.generated Sat Mar 19 18:40:55 EET 2022
     */
    int updateByPrimaryKey(Category record);
}