package mybatis.mapper;

import java.util.List;
import mybatis.model.Item;
import org.mybatis.cdi.Mapper;

@Mapper
public interface ItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ITEM
     *
     * @mbg.generated Sat Mar 19 18:40:55 EET 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ITEM
     *
     * @mbg.generated Sat Mar 19 18:40:55 EET 2022
     */
    int insert(Item record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ITEM
     *
     * @mbg.generated Sat Mar 19 18:40:55 EET 2022
     */
    Item selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ITEM
     *
     * @mbg.generated Sat Mar 19 18:40:55 EET 2022
     */
    List<Item> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ITEM
     *
     * @mbg.generated Sat Mar 19 18:40:55 EET 2022
     */
    int updateByPrimaryKey(Item record);
}