package mybatis.model;

public class Category {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CATEGORY.ID
     *
     * @mbg.generated Sat Mar 19 18:40:55 EET 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CATEGORY.NAME
     *
     * @mbg.generated Sat Mar 19 18:40:55 EET 2022
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CATEGORY.ID
     *
     * @return the value of PUBLIC.CATEGORY.ID
     *
     * @mbg.generated Sat Mar 19 18:40:55 EET 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CATEGORY.ID
     *
     * @param id the value for PUBLIC.CATEGORY.ID
     *
     * @mbg.generated Sat Mar 19 18:40:55 EET 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CATEGORY.NAME
     *
     * @return the value of PUBLIC.CATEGORY.NAME
     *
     * @mbg.generated Sat Mar 19 18:40:55 EET 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CATEGORY.NAME
     *
     * @param name the value for PUBLIC.CATEGORY.NAME
     *
     * @mbg.generated Sat Mar 19 18:40:55 EET 2022
     */
    public void setName(String name) {
        this.name = name;
    }
}