package mybatis.model;

public class Item {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ITEM.ID
     *
     * @mbg.generated Sat Mar 19 18:40:55 EET 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ITEM.NAME
     *
     * @mbg.generated Sat Mar 19 18:40:55 EET 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ITEM.PRICE
     *
     * @mbg.generated Sat Mar 19 18:40:55 EET 2022
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ITEM.QUANTITY
     *
     * @mbg.generated Sat Mar 19 18:40:55 EET 2022
     */
    private Integer quantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ITEM.CATEGORY_ID
     *
     * @mbg.generated Sat Mar 19 18:40:55 EET 2022
     */
    private Long categoryId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ITEM.ID
     *
     * @return the value of PUBLIC.ITEM.ID
     *
     * @mbg.generated Sat Mar 19 18:40:55 EET 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ITEM.ID
     *
     * @param id the value for PUBLIC.ITEM.ID
     *
     * @mbg.generated Sat Mar 19 18:40:55 EET 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ITEM.NAME
     *
     * @return the value of PUBLIC.ITEM.NAME
     *
     * @mbg.generated Sat Mar 19 18:40:55 EET 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ITEM.NAME
     *
     * @param name the value for PUBLIC.ITEM.NAME
     *
     * @mbg.generated Sat Mar 19 18:40:55 EET 2022
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ITEM.PRICE
     *
     * @return the value of PUBLIC.ITEM.PRICE
     *
     * @mbg.generated Sat Mar 19 18:40:55 EET 2022
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ITEM.PRICE
     *
     * @param price the value for PUBLIC.ITEM.PRICE
     *
     * @mbg.generated Sat Mar 19 18:40:55 EET 2022
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ITEM.QUANTITY
     *
     * @return the value of PUBLIC.ITEM.QUANTITY
     *
     * @mbg.generated Sat Mar 19 18:40:55 EET 2022
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ITEM.QUANTITY
     *
     * @param quantity the value for PUBLIC.ITEM.QUANTITY
     *
     * @mbg.generated Sat Mar 19 18:40:55 EET 2022
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ITEM.CATEGORY_ID
     *
     * @return the value of PUBLIC.ITEM.CATEGORY_ID
     *
     * @mbg.generated Sat Mar 19 18:40:55 EET 2022
     */
    public Long getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ITEM.CATEGORY_ID
     *
     * @param categoryId the value for PUBLIC.ITEM.CATEGORY_ID
     *
     * @mbg.generated Sat Mar 19 18:40:55 EET 2022
     */
    public void setCategoryId(Long categoryId) {
        this.categoryId = categoryId;
    }
}