package mybatis.model;

public class Shop {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SHOP.ID
     *
     * @mbg.generated Sat Mar 19 18:40:55 EET 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SHOP.ADDRESS
     *
     * @mbg.generated Sat Mar 19 18:40:55 EET 2022
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SHOP.NAME
     *
     * @mbg.generated Sat Mar 19 18:40:55 EET 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SHOP.NUMBER
     *
     * @mbg.generated Sat Mar 19 18:40:55 EET 2022
     */
    private String number;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SHOP.ID
     *
     * @return the value of PUBLIC.SHOP.ID
     *
     * @mbg.generated Sat Mar 19 18:40:55 EET 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SHOP.ID
     *
     * @param id the value for PUBLIC.SHOP.ID
     *
     * @mbg.generated Sat Mar 19 18:40:55 EET 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SHOP.ADDRESS
     *
     * @return the value of PUBLIC.SHOP.ADDRESS
     *
     * @mbg.generated Sat Mar 19 18:40:55 EET 2022
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SHOP.ADDRESS
     *
     * @param address the value for PUBLIC.SHOP.ADDRESS
     *
     * @mbg.generated Sat Mar 19 18:40:55 EET 2022
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SHOP.NAME
     *
     * @return the value of PUBLIC.SHOP.NAME
     *
     * @mbg.generated Sat Mar 19 18:40:55 EET 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SHOP.NAME
     *
     * @param name the value for PUBLIC.SHOP.NAME
     *
     * @mbg.generated Sat Mar 19 18:40:55 EET 2022
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SHOP.NUMBER
     *
     * @return the value of PUBLIC.SHOP.NUMBER
     *
     * @mbg.generated Sat Mar 19 18:40:55 EET 2022
     */
    public String getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SHOP.NUMBER
     *
     * @param number the value for PUBLIC.SHOP.NUMBER
     *
     * @mbg.generated Sat Mar 19 18:40:55 EET 2022
     */
    public void setNumber(String number) {
        this.number = number;
    }
}